apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: loki
spec:
  tenants:
    mode: openshift-network
  managementState: Managed
  replicationFactor: 1
  storage:
    schemas:
      - effectiveDate: '2020-10-11'
        version: v11
    secret:
      name: lokistack-dev-s3
      type: s3
  size: 1x.extra-small
  storageClassName: gp2-csi
