---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-netobserv
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: netobserv, operator: In, values: ["true"]}
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-netobserv
placementRef:
  name: placement-policy-netobserv
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: netobserv
  kind: Policy
  apiGroup: policy.open-cluster-management.io
- name: netobserv-flowcollector
  kind: Policy
  apiGroup: policy.open-cluster-management.io
